version: '2'

services:
  mesos-master:
    image: mesos-base
    container_name: mesos-master
    hostname: mesos-master
    ports:
      - "5050:5050"
    entrypoint: ["mesos-master.sh", "--ip=0.0.0.0", "--work_dir=/var/lib/mesos"]
  mesos-agent1:
    image: mesos-base
    container_name: mesos-agent1
    hostname: mesos-agent1
    privileged: true
    network_mode: "host"
    entrypoint: ["mesos-agent.sh", "--master=127.0.0.1:5050", "--work_dir=/var/lib/mesos", "--no-systemd_enable_support"]
    depends_on:
      - mesos-master
